# Generated by Django 3.2.12 on 2022-05-19 03:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('profile_path', models.CharField(max_length=200, null=True)),
                ('character', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('profile_path', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='NowPlayingMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adult', models.BooleanField()),
                ('title', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
                ('popularity', models.FloatField()),
                ('vote_average', models.FloatField()),
                ('overview', models.TextField()),
                ('youtube_key', models.CharField(max_length=200)),
                ('backdrop_path', models.CharField(max_length=200, null=True)),
                ('poster_path', models.CharField(max_length=200, null=True)),
                ('actors', models.ManyToManyField(related_name='nowplaying_actors', to='movies.Actor')),
                ('director', models.ManyToManyField(related_name='nowplaying_director', to='movies.Director')),
                ('genres', models.ManyToManyField(related_name='nowplaying_movies', to='movies.Genre')),
                ('like_users', models.ManyToManyField(related_name='like_nowplaying_movies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PopularMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adult', models.BooleanField()),
                ('title', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
                ('popularity', models.FloatField()),
                ('vote_average', models.FloatField()),
                ('overview', models.TextField()),
                ('youtube_key', models.CharField(max_length=200)),
                ('backdrop_path', models.CharField(max_length=200, null=True)),
                ('poster_path', models.CharField(max_length=200, null=True)),
                ('actors', models.ManyToManyField(related_name='popular_actors', to='movies.Actor')),
                ('director', models.ManyToManyField(related_name='popular_director', to='movies.Director')),
                ('genres', models.ManyToManyField(related_name='popular_movies', to='movies.Genre')),
                ('like_users', models.ManyToManyField(related_name='like_popular_movies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UpcomingMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adult', models.BooleanField()),
                ('title', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
                ('popularity', models.FloatField()),
                ('vote_average', models.FloatField()),
                ('overview', models.TextField()),
                ('youtube_key', models.CharField(max_length=200)),
                ('backdrop_path', models.CharField(max_length=200, null=True)),
                ('poster_path', models.CharField(max_length=200, null=True)),
                ('actors', models.ManyToManyField(related_name='upcoming_actors', to='movies.Actor')),
                ('director', models.ManyToManyField(related_name='upcoming_director', to='movies.Director')),
                ('genres', models.ManyToManyField(related_name='upcoming_movies', to='movies.Genre')),
                ('like_users', models.ManyToManyField(related_name='like_upcoming_movies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('rank', models.IntegerField()),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('like_users', models.ManyToManyField(related_name='like_reviews', to=settings.AUTH_USER_MODEL)),
                ('nowplaying_movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.nowplayingmovie')),
                ('popular_movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.popularmovie')),
                ('upcoming_movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.upcomingmovie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_review', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
