# Generated by Django 3.2.12 on 2022-05-19 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nowplayingmovie',
            name='movie_id',
        ),
        migrations.RemoveField(
            model_name='popularmovie',
            name='movie_id',
        ),
        migrations.RemoveField(
            model_name='upcomingmovie',
            name='movie_id',
        ),
    ]
