# Generated by Django 3.2.12 on 2022-05-20 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20220519_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='nowplaying_movie',
        ),
        migrations.RemoveField(
            model_name='review',
            name='upcoming_movie',
        ),
    ]
