# Generated by Django 3.2.12 on 2022-05-23 08:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0004_auto_20220520_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='like_users',
            field=models.ManyToManyField(related_name='like_actor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='director',
            name='like_users',
            field=models.ManyToManyField(related_name='like_director', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='genre',
            name='like_users',
            field=models.ManyToManyField(related_name='like_genres', to=settings.AUTH_USER_MODEL),
        ),
    ]
