# Generated by Django 3.2.12 on 2022-05-24 12:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0005_auto_20220523_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='hate_users',
            field=models.ManyToManyField(related_name='hate_genres', to=settings.AUTH_USER_MODEL),
        ),
    ]
