# Generated by Django 3.2.12 on 2022-05-24 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_genre_hate_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='like_users',
        ),
        migrations.AddField(
            model_name='genre',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
