# Generated by Django 3.2.12 on 2022-05-25 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_auto_20220524_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='unlike',
            field=models.BooleanField(default=False),
        ),
    ]
