# Generated by Django 3.2.12 on 2022-05-25 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_genre_unlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='popularmovie',
            name='genre_score',
            field=models.IntegerField(default=0),
        ),
    ]
